config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'welcome/index'
  resources :users
  root to: 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collaborators
  has_many :wikis, through: :collaborators
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    link_to image_tag(gravatar_url, alt: user.username, class: "gravatar"), 'https://en.gravatar.com/emails/', target: '_blank'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Blocipedia", root_path, class: "navbar-brand white-text"  %>
        </div>

        
          <% if current_user %>
            <!-- <%= link_to "My Lists", user_path(current_user), class: "navbar-text" %> -->
            <form class="navbar-form navbar-right login-blurb">
              <%= gravatar_for current_user %>
              <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <%= current_user.username %> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Home", current_user %></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </div>
            </form>

          <% else %>
            <%= form_for(:user, url: session_path(:user), html: {class: "navbar-form navbar-right"}) do |f| %>
               <div class="form-group">
                <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
              </div>
              <%= f.submit "Sign in", class: 'btn btn-success' %>
            <% end %>
          <% end %>
        
        </div>
      </nav>


      <% if flash[:notice] %>
       <div class="alert alert-success flash-notice">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
      <% elsif flash[:error] %>
       <div class="alert alert-danger flash-notice">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:error] %>
       </div>
      <% elsif flash[:alert] %>
       <div class="alert alert-warning flash-notice">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
      <% end %>

      <div class='container'>
        <%= yield %>
      </div>


<div class="container">
  <hr>
  <footer>
    <p>© Brock Cooper and Bloc.io 2015</p>
  </footer>
</div> <!-- /container -->

</body>
</html>

app/views/welcome/index.html.erb
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron" id="main-jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1 class="white-text">Blocipedia</h1>
         <p class="white-text">Create collaborative wikis that you can share with the whole world or make them private for just your and your friends.</p>
      </div>
      <% if !current_user %>
      <div class="col-md-5">
            <br>
            <%= form_for(:user, url: registration_path(:user)) do |f| %>
              <div class="form-group">
                <%= f.text_field :username, class: 'form-control', placeholder: "Enter Username" %>
              </div>
              <div class="form-group">
                <%= f.email_field :email, class: 'form-control', placeholder: "Enter Email" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, class: 'form-control', placeholder: "Enter Password" %>
              </div>
              <div class="form-group">
                <%= f.submit "Sign up for Blocipedia", class: 'btn btn-primary btn-lg col-md-12' %>
              </div>
              <div class="form-group">
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>
<container>